### ISSUE TITLE
Short term roadmap

### ISSUE THREAD

**Issue by krzkaczor** [ethereum-ts/TypeChain#171]
- [x] snapshots for generated code in tests to prevent regressions
- [x] [ABI parser improvements](https://github.com/ethereum-ts/TypeChain/issues/106)
- [x] extract targets into separate packages and make this repository a monorepo
- [x] update readme docs
- [x] update/write new medium post
