### ISSUE TITLE
Version 2 roadmap

### ISSUE THREAD

**Issue by krzkaczor** [ethereum-ts/TypeChain#204]
Branch: `next-ver-2`

- [x] normalize generated contract names (BREAKING)
- [x] abi parser should normalize empty names to undefineds (BREAKING)
- [x] change names of target packages since NPM keeps on flagging them as spam 😢

**Comment by krzkaczor** [comment]
https://github.com/ethereum-ts/TypeChain/pull/219

**Comment by krzkaczor** [comment]
https://github.com/ethereum-ts/TypeChain/releases/tag/v2.0.0
