### ISSUE TITLE
Version 5 roadmap

### ISSUE THREAD

**Issue by krzkaczor** [ethereum-ts/TypeChain#362]
- [ ] Remove `ts-generator`
- [ ] Incremental generation
- [ ] Ethers-v5 incremental generation
- [ ] Better support for hardhat in Ethers-v5
- [ ] Add a flag NOT to generate full signatures when they are not needed https://github.com/ethereum-ts/TypeChain/issues/357
- [ ] Support multiple files in CLI: https://github.com/ethereum-ts/TypeChain/issues/214
